#!/bin/bash
gcloud compute instances delete head-node --zone europe-west1-c
gcloud compute instances delete mpi-node01 --zone europe-west1-c
gcloud compute instances delete mpi-node02 --zone europe-west1-c
